### ISSUE TITLE
Проблема с востановлением пароля

### ISSUE THREAD

**Issue by Alerion** [RaD/djbookru#261]
"Пытаюсь восстановить пароль. Приходит письмо - но при переходе по ссылке в нем получаю ответ, что эта ссылка уже была использована. При запросе новой ссылки приходит письмо с той же самой ссылкой"

**Comment by RaD** [comment]
Также была ошибка с неправильным URL.

**Comment by Alerion** [comment]
Вроде починили. Добавлю тестов еще. Пока не закрываем.
