### ISSUE TITLE
Индексирование тем на форуме не работает

### ISSUE THREAD

**Issue by RaD** [RaD/djbookru#270]
Журнал:

    File "/home/django/djbookru/src/forum/search_indexes.py", line 23, in prepare
    self.prepared_data = super(TopicIndex, self).prepare(obj)

    django.template.base.TemplateDoesNotExist: search/indexes/forum/topic_text.txt

**Comment by Alerion** [comment]
А это не снова проблемы деплоя? Есть такой шаблон https://github.com/RaD/djbookru/blob/master/src/templates/search/indexes/forum/topic_text.txt
